<Project>
    <Import Project="Directory.Build.GospelPresenter.props"
            Condition="Exists('Directory.Build.GospelPresenter.props')" />

    <PropertyGroup>
        <!-- App Identifier -->
        <ApplicationId>com.gospelpresenter.app</ApplicationId>
    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'android'"
                  Include="Resources\AppIcon\appicon.svg"
                  ForegroundFile="Resources\AppIcon\appiconfg.svg"
                  Color="#ffffff"/>
        <MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'"
                  Include="Resources\AppIcon\appicon.svg"
                  ForegroundFile="Resources\AppIcon\appiconfg.svg"
                  Color="#ffffff"
                  ForegroundScale="0.65" />
    </ItemGroup>
</Project>
