<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="xunit" Version="2.9.2"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GospelPresenter.Shared\GospelPresenter.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="StanForDClassic">
        <HintPath>..\GospelPresenter.Shared\StanForDClassic.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF.ghd">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Fastighet.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Fastighet.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Fastighet.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Fastighet.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Fornpunkt.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Fornpunkt.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Fornpunkt.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Fornpunkt.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Granser.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Granser.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Granser.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Granser.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDEditLine.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDEditLine.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDEditLine.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDEditPoint.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDEditPoint.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDEditPoint.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDEditPolygon.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDEditPolygon.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDEditPolygon.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDTrackLayer.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDTrackLayer.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\MachineIDTrackLayer.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto1.jgw">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto1.jpg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto2.jgw">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto2.jpg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto3.jgw">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto3.jpg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto4.jgw">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto4.jpg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto5.jgw">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Ortofoto5.jpg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Sodra_DT_3.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktlinjer.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktlinjer.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktlinjer.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktlinjer.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktsymboler.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktsymboler.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktsymboler.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktsymboler.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Trakttext.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Trakttext.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Trakttext.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Trakttext.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktytor.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktytor.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktytor.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Traktytor.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Upplag.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Upplag.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Upplag.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Upplag.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Vagar.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Vagar.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Vagar.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Vagar.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Vagar_ovriga.dbf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Vagar_ovriga.prj">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Vagar_ovriga.shp">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Resources\DERWINGER_STAFFAN_M_FL_2821039A10_429979_SWEREF\Vagar_ovriga.shx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
