<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Version>1.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GospelPresenter.ServiceDefaults\GospelPresenter.ServiceDefaults.csproj" />
        <ProjectReference Include="..\GospelPresenter.Shared\GospelPresenter.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
      <PackageReference Include="prometheus-net.AspNetCore.HealthChecks" Version="8.2.1" />
      <PackageReference Include="Serilog" Version="4.3.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
    </ItemGroup>

</Project>
