using GospelPresenter.Shared.State;

namespace GospelPresenter.Shared.Services;

/// <summary>
/// The themes Gospel Presenter ships. Authored here rather than as migration data so that fixing one
/// is an ordinary code change that reaches every environment — including the mock database and the
/// tests — without a migration.
///
/// Ids are stable slugs and must never be reused for a different look: presentations point at them.
/// No built-in theme may render main text larger than <see cref="SlideTheme.Classic"/> does; see
/// adr/0001-slide-themes.md and BuiltInThemeTests, which fails rather than trusting anyone's eye.
///
/// The four themes exist to cover the model: a reference point, a background colour that is not black,
/// dark text on a light background, and a background image with a scrim. A property no theme uses is
/// untested code that will break when the theme editor arrives.
/// </summary>
public static class BuiltInThemes
{
    public const string ClassicId = "classic";
    public const string MidnightId = "midnight";
    public const string DaylightId = "daylight";
    public const string AuroraId = "aurora";

    /// <summary>
    /// Theme art is generated by scripts/generate-theme-backgrounds.py rather than sourced from a photo
    /// library: these files are redistributed with every self-hosted installation, so the licence has to
    /// be ours. The hash must match the file — <see cref="BuiltInThemeTests"/> checks it.
    /// </summary>
    public const string AuroraBackgroundAsset = "aurora/background";
    public const string AuroraBackgroundHash = "7bcf41fdc25328d2";

    public static readonly IReadOnlyList<BuiltInTheme> All =
    [
        new(ClassicId, 0, SlideTheme.Classic),
        new(MidnightId, 1, Midnight),
        new(DaylightId, 2, Daylight),
        new(AuroraId, 3, Aurora)
    ];

    /// <summary>
    /// Deep blue rather than black, with a cleaner typeface. Size and line come from the baseline; the
    /// weight is lighter than Classic's, which is a deliberate variation rather than a firmer setting.
    /// </summary>
    private static SlideTheme Midnight => new()
    {
        Song = new SlideStyle
        {
            Background = MidnightBackground,
            MainText = new SlideTextStyle
            {
                FontFamily = SlideFontFamilies.Inter,
                FontWeight = 600
            },
            Credits = MidnightCredits
        },
        BibleText = new SlideStyle
        {
            Background = MidnightBackground,
            MainText = new SlideTextStyle
            {
                FontFamily = SlideFontFamilies.Inter,
                FontWeight = 500,
                Align = SlideTextAlign.Left
            },
            Credits = MidnightCredits
        },
        Media = MidnightBackground
    };

    /// <summary>
    /// The one light theme, for LED walls and rooms too bright for a dark slide. It is also what proves
    /// the colour model works in both directions.
    /// </summary>
    private static SlideTheme Daylight => new()
    {
        Song = new SlideStyle
        {
            Background = DaylightBackground,
            MainText = new SlideTextStyle
            {
                FontFamily = SlideFontFamilies.Lato,
                Color = DaylightInk
            },
            Credits = DaylightCredits
        },
        BibleText = new SlideStyle
        {
            Background = DaylightBackground,
            MainText = new SlideTextStyle
            {
                FontFamily = SlideFontFamilies.Lato,
                Color = DaylightInk,
                Align = SlideTextAlign.Left
            },
            Credits = DaylightCredits
        },
        Media = DaylightBackground
    };

    /// <summary>
    /// Background image with a scrim and a text shadow. Media keeps colour only — a photo behind a photo
    /// never looks deliberate.
    /// </summary>
    private static SlideTheme Aurora => new()
    {
        Song = new SlideStyle
        {
            Background = AuroraBackground,
            MainText = new SlideTextStyle
            {
                FontFamily = SlideFontFamilies.Montserrat,
                FontWeight = 500,
                Shadow = true
            },
            Credits = AuroraCredits
        },
        BibleText = new SlideStyle
        {
            Background = AuroraBackground,
            MainText = new SlideTextStyle
            {
                FontFamily = SlideFontFamilies.Montserrat,
                Align = SlideTextAlign.Left,
                Shadow = true
            },
            Credits = AuroraCredits
        },
        Media = new SlideBackground { Color = "#0d1024" }
    };

    private static SlideBackground MidnightBackground => new() { Color = "#0b1b3a" };

    private static SlideBackground DaylightBackground => new() { Color = "#faf7f2" };

    private static SlideBackground AuroraBackground => new()
    {
        Color = "#0d1024",
        Image = new SlideBackgroundImage
        {
            Source = SlideImageSource.BuiltInAsset,
            Value = AuroraBackgroundAsset,
            ContentHash = AuroraBackgroundHash
        },
        Fit = SlideBackgroundFit.Cover,
        ScrimPercent = 45
    };

    private static SlideTextStyle MidnightCredits => new()
    {
        FontSize = 40,
        LineHeight = 1.2,
        FontFamily = SlideFontFamilies.Inter,
        Color = "rgba(255, 255, 255, 0.45)",
        Align = SlideTextAlign.Left
    };

    private const string DaylightInk = "#141210";

    private static SlideTextStyle DaylightCredits => new()
    {
        FontSize = 40,
        LineHeight = 1.2,
        FontFamily = SlideFontFamilies.Lato,
        Color = "rgba(20, 18, 16, 0.55)",
        Align = SlideTextAlign.Left
    };

    private static SlideTextStyle AuroraCredits => new()
    {
        FontSize = 40,
        LineHeight = 1.2,
        FontFamily = SlideFontFamilies.Montserrat,
        Color = "rgba(255, 255, 255, 0.5)",
        Align = SlideTextAlign.Left,
        Shadow = true
    };
}

public record BuiltInTheme(string Id, int SortOrder, SlideTheme Definition);
