<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
<!-- Attempt to fix publish error on TeamCity (https://github.com/dotnet/aspnetcore/issues/59291) -->
        <CompressionEnabled>false</CompressionEnabled>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Google.Protobuf" Version="3.29.3" />
        <PackageReference Include="Grpc.Tools" Version="2.71.0" PrivateAssets="All" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.5" />
        <PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.11" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="SkiaSharp" Version="3.119.2" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.2" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Proto\propresenter.proto" GrpcServices="None" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot\**">
            <PublishFolderType>Content</PublishFolderType>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Components\Map\Map.razor" />
      <UpToDateCheckInput Remove="Components\Map\MapFeatureSelector.razor" />
      <UpToDateCheckInput Remove="Components\Login\Login.razor" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="HttpClients\" />
    </ItemGroup>

    <Import Project="TailwindCssCli.targets" />

</Project>
