#!/usr/bin/env bash
#
# Registers a development build's callback scheme with the desktop environment,
# so the device sign-in callback can find the app.
#
# The scheme depends on which build scheme the app was built with, because each
# installation answers on its own — see GospelPresenter.Desktop's
# Directory.Build.GospelPresenter*.props. A `dotnet run` build is the Local
# scheme unless you passed -p:Scheme, hence the default below.
#
# A packaged build does this itself: electron-builder writes a .desktop file
# naming the scheme, and Electron's setAsDefaultProtocolClient has something to
# point at. Running the app with `dotnet run` leaves no .desktop file anywhere,
# so the browser gets the callback URL and finds no owner for it — the sign-in
# ends with "No apps available" and the app waits for a callback that never
# arrives.
#
# The handler starts the same Electron binary with the URL appended. The app
# holds Electron's single-instance lock (package.json: singleInstance), so that
# second launch quits immediately and forwards its arguments to the instance
# already running, where ElectronDeviceSignIn reads the URL out of argv.
#
#   ./scripts/register-url-scheme-linux.sh            install for Debug
#   ./scripts/register-url-scheme-linux.sh Release    install for Release
#   ./scripts/register-url-scheme-linux.sh --remove   undo
#
# GP_CALLBACK_SCHEME overrides the scheme, for a build made with a different
# -p:Scheme. Pass the same value to --remove that you installed with.
#
set -euo pipefail

SCHEME="${GP_CALLBACK_SCHEME:-gospelpresenter-local}"
DESKTOP_FILE="${XDG_DATA_HOME:-$HOME/.local/share}/applications/$SCHEME-url-handler.desktop"
HANDLER="${XDG_DATA_HOME:-$HOME/.local/share}/$SCHEME/url-handler.sh"

if [[ "${1:-}" == "--remove" ]]; then
    rm -f "$DESKTOP_FILE" "$HANDLER"
    rmdir --ignore-fail-on-non-empty "$(dirname "$HANDLER")" 2>/dev/null || true
    update-desktop-database "$(dirname "$DESKTOP_FILE")" 2>/dev/null || true
    echo "Removed the $SCHEME:// handler."
    exit 0
fi

CONFIGURATION="${1:-Debug}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$REPO_ROOT/GospelPresenter/GospelPresenter.Desktop/bin/$CONFIGURATION/net10.0"

if [[ ! -x "$APP_DIR/.electron/node_modules/electron/dist/electron" ]]; then
    echo "No Electron binary under $APP_DIR/.electron." >&2
    echo "Build the desktop app first: dotnet build GospelPresenter/GospelPresenter.Desktop" >&2
    exit 1
fi

mkdir -p "$(dirname "$HANDLER")" "$(dirname "$DESKTOP_FILE")"

cat > "$HANDLER" <<EOF
#!/usr/bin/env bash
# Generated by scripts/register-url-scheme-linux.sh — re-run it after moving the
# repository or switching build configuration.
cd "$APP_DIR/.electron" || exit 1
exec ./node_modules/electron/dist/electron \\
    main.js -unpackeddotnet -electronforcedport=0 \\
    "$APP_DIR/GospelPresenter.Desktop.dll" "\$1"
EOF
chmod +x "$HANDLER"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Gospel Presenter ($SCHEME:// handler, $CONFIGURATION build)
Exec=$HANDLER %u
Terminal=false
NoDisplay=true
MimeType=x-scheme-handler/$SCHEME;
EOF

update-desktop-database "$(dirname "$DESKTOP_FILE")" 2>/dev/null || true
xdg-mime default "$(basename "$DESKTOP_FILE")" "x-scheme-handler/$SCHEME"

echo "Registered $SCHEME:// → $APP_DIR"
echo "Handler:  $HANDLER"
echo "Desktop:  $DESKTOP_FILE"
